{{- if .Values.istio.enabled }}
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "helm.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  gateways:
    - {{ template "helm.fullname" . }}
  hosts:
    - {{ template "helm.fullname" . }}.local
  - {{ .Values.ingress.host }}
  http:
    - name: primary
      route:
        - destination:
            host: {{ template "helm.fullname" . }}
            port:
              number: 80
          weight: 100
        - destination:
            host: {{ template "helm.fullname" . }}-canary
            port:
              number: 80
          weight: 0

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "helm.fullname" . }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
  {{- end }}