apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "helm.fullname" . }}