apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
  {{- if .Values.istio.enabled -}}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  {{- else -}}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
  {{- if .Values.istio.enabled -}}
    app: {{ template "helm.fullname" . }}
  {{- else -}}
    app: {{ template "helm.fullname" . }}
  {{- end }}

