apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
    app: {{ template "helm.fullname" . }}
