apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
